### **Apriori Algorithm**

In [ ]:
pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
#data = pd.read_csv('/content/sample_data/emp.csv')
#data.head()
data=[['A','B','C','D','E','F'],
      ['G','B','C','D','E','F'],
      ['A','Z','D','E'],
      ['A','X','V','D','F'],
      ['V','B','L','D','I','E']]

In [ ]:
#data = pd.read_csv('/content/sample_data/emp.csv', header=None)
num=len(data)
print(num)

5

In [ ]:
#association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
#association_results = list(association_rules)
#print(association_rules)

In [ ]:
#fk lor item in association_rules:                                          
#   pair = item[0] 
#  items = [x for x in pair]
#    print("Rule: " + items[0] + " -> " + items[1])

#   print("Support: " + str(item[1]))

  
#    print("Confidence: " + str(item[2][0][2]))
#   print("Lift: " + str(item[2][0][3]))
#    print("=====================================")

In [ ]:
te=TransactionEncoder()
te_ary=te.fit(data).transform(data)
te_ary

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False, False, False],
       [False,  True,  True,  True,  True,  True,  True, False, False,
        False, False, False],
       [ True, False, False,  True,  True, False, False, False, False,
        False, False,  True],
       [ True, False, False,  True, False,  True, False, False, False,
         True,  True, False],
       [False,  True, False,  True,  True, False, False,  True,  True,
         True, False, False]])

In [ ]:
df=pd.DataFrame(te_ary,columns=te.columns_)
df
#print(df)

       A      B      C     D      E  ...      I      L      V      X      Z
0   True   True   True  True   True  ...  False  False  False  False  False
1  False   True   True  True   True  ...  False  False  False  False  False
2   True  False  False  True   True  ...  False  False  False  False   True
3   True  False  False  True  False  ...  False  False   True   True  False
4  False   True  False  True   True  ...   True   True   True  False  False

[5 rows x 12 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(df,min_support=0.5,use_colnames=True)
frequent_itemsets

    support   itemsets
0       0.6        (A)
1       0.6        (B)
2       1.0        (D)
3       0.8        (E)
4       0.6        (F)
5       0.6     (A, D)
6       0.6     (B, D)
7       0.6     (B, E)
8       0.8     (E, D)
9       0.6     (F, D)
10      0.6  (E, B, D)

## **Association Rule Mining**

In [ ]:
from mlxtend.frequent_patterns import association_rules
res=association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7)
res[['antecedents','consequents','support','confidence','lift']]

   antecedents consequents  support  confidence  lift
0          (A)         (D)      0.6        1.00  1.00
1          (B)         (D)      0.6        1.00  1.00
2          (B)         (E)      0.6        1.00  1.25
3          (E)         (B)      0.6        0.75  1.25
4          (E)         (D)      0.8        1.00  1.00
5          (D)         (E)      0.8        0.80  1.00
6          (F)         (D)      0.6        1.00  1.00
7       (B, E)         (D)      0.6        1.00  1.00
8       (D, E)         (B)      0.6        0.75  1.25
9       (B, D)         (E)      0.6        1.00  1.25
10         (E)      (B, D)      0.6        0.75  1.25
11         (B)      (D, E)      0.6        1.00  1.25

In [ ]:
res1=res[res['confidence']>=1]
res1[['antecedents','consequents','support','confidence','lift']]

   antecedents consequents  support  confidence  lift
0          (A)         (D)      0.6         1.0  1.00
1          (B)         (D)      0.6         1.0  1.00
2          (B)         (E)      0.6         1.0  1.25
4          (E)         (D)      0.8         1.0  1.00
6          (F)         (D)      0.6         1.0  1.00
7       (B, E)         (D)      0.6         1.0  1.00
9       (B, D)         (E)      0.6         1.0  1.25
11         (B)      (D, E)      0.6         1.0  1.25